# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'H264VideoDecoder2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'VideoDecoder'

  # Pods for H264VideoDecoder2

end
